namespace BSPFileReader
{

    public enum LumpType : int
    {
        ENTITIES = 0,
        PLANES,
        TEXDATA,
        VERTEXES,
        VISIBILITY,
        NODES,
        TEXINFO,
        FACES,
        LIGHTING,
        OCCLUSION,
        LEAFS,
        FACEIDS,
        EDGES,
        SURFEDGES,
        MODELS,
        WORLDLIGHTS,
        LEAFFACES,
        LEAFBRUSHES,
        BRUSHES,
        BRUSHSIDES,
        AREAS,
        AREAPORTALS,
        PORTALS,
        UNUSED0,
        PROPCOLLISION,
        CLUSTERS,
        UNUSED1,
        PROPHULLS,
        PORTALVERTS,
        UNUSED2,
        PROPHULLVERTS,
        CLUSERPORTALS,
        UNUSED3,
        PROPTRIS,
        DISPINFO,
        ORIGINALFACES,
        PHYSDISP,
        PHYSCOLLIDE,
        VERTNORMALS,
        VERTNORMALINDICES,
        DISP_LIGHTMAP_ALPHAS,
        DISP_VERTS,
        DISP_LIGHTMAP_SAMPLE_POSITIONS,
        GAME_LUMP,
        LEAFWATERDATA,
        PRIMITIVES,
        PRIMVERTS,
        PRIMINDICES,
        PAKFILE,
        CLIPPORTALVERTS,
        CUBEMAPS,
        TEXDATA_STRING_DATA,
        TEXDATA_STRING_TABLE,
        OVERLAYS,
        LEAFMINDISTTOWTER,
        FACE_MACRO_TEXTURE_INFO,
        DISP_TRIS,
        PHYSCOLLIDESURFACE,
        PROP_BLOB,
        WATEROVERALYS,
        LIGHTMAPPAGES,
        LEAF_AMBIENT_INDEX_HDR,
        LIGHTMAPPAGEINFOS,
        LEAF_AMBIENT_INDEX,
        LIGHTING_HDR,
        WORLDLIGHTS_HDR,
        LEAF_AMBIENT_LIGHTING_HDR,
        LEAF_AMBIENT_LIGHTING,
        XZIPPAKFILE,
        FACES_HDR,
        MAP_FLAGS,
        OVERLAY_FADES,
        OVERLAY_SYSTEM_LEVELS,
        PHYSLEVEL,
        DISP_MULTIBLEND
    }

    public enum BrushContents : int
    {
        EMPTY = 0,
        SOLID = 0x1,
        WINDOW = 0x2,
        AUX = 0x4,
        GRATE = 0x8,
        SLIME,
        WATER,
        MIST,
        OPAQUE,
        TESTFOGVOLUME,
        UNUSED,
        UNUSED6,
        TEAM1,
        TEAM2,
        IGNORE_NODRAW_OPAQUE,
        MOVEABLE,
        AREAPORTAL,
        PLAYERCLIP,
        MONSTERCLIP,
        CURRENT_0,
        CURRENT_90,
        CURRENT_180,
        CURRENT_270,
        CURRENT_UP,
        CURRENT_DOWN,
        ORIGIN,
        MONSTER,
        DEBRIS,
        DETAIL,
        TRANSLUCENT,
        LADDER,
        HITBOX
    }

}
